const MONGODB_URI = process.env['MONGODB_URI']

const CLOUDINARY_CLOUD_NAME = process.env['CLOUDINARY_CLOUD_NAME']
const CLOUDINARY_API_KEY = process.env['CLOUDINARY_API_KEY']
const CLOUDINARY_API_SECRET = process.env['CLOUDINARY_API_SECRET']

module.exports = {
    MONGODB_URI,
    CLOUDINARY_CLOUD_NAME,
    CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET
}